
spring:
  application:
    name: monitoring-service
  influxdb:
    url: http://localhost:8086
    username: admin
    password: admin
    database: monitorServiceDB
    retention-policy: autogen
    series: flux
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
    #current service name to be used by the eureka server
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
logging:
  level:
    com.example.howtodoinjava: DEBUG
